# Generated by Django 5.1.1 on 2024-10-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction1', models.CharField(max_length=10)),
                ('angle_degrees', models.IntegerField()),
                ('angle_minutes', models.IntegerField()),
                ('angle_seconds', models.IntegerField(default=0)),
                ('direction2', models.CharField(max_length=10)),
                ('length', models.FloatField()),
                ('site_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_points', to='siteplans.siteplan')),
            ],
        ),
    ]
