# Generated by Django 5.1.1 on 2024-10-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundarypoint',
            name='direction1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='boundarypoint',
            name='direction2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='boundarypoint',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
